### ISSUE TITLE
没有GPU的条件，使用CPU能否运行呢？

### ISSUE THREAD

**Issue by xqyi** [RiseInRose/MiniGPT-4-ZH#2]

**Comment by hebochang** [comment]
恐怕是不能

**Comment by WhiteEnzuo** [comment]
能，只是时间有亿点点久而已

**Comment by RiseInRose** [comment]
可以，速度会特别慢。而且需要50G 左右内存。如果内存也不够，理论上可以使用硬盘当内存。真这样做了，推理速度基本不能接受

**Comment by Maknee** [comment]
[minigpt4.cpp](https://github.com/Maknee/minigpt4.cpp)



![image.png](https://raw.githubusercontent.com/Maknee/minigpt4.cpp/master/assets/webui_demo.png)
