### ISSUE TITLE
按照流程部署好以后执行demo，出现乱码回复

### ISSUE THREAD

**Issue by huzhenxing** [RiseInRose/MiniGPT-4-ZH#5]
我是按照这篇文章给的说明安装的，模型没有进行训练的步骤，然后执行的demo.py查看效果，结果用英文输入语句结果出现乱码结果。是模型融合的不对？还是检查点有问题？

**Comment by coding-alt** [comment]
运行 demo.py也同样出现乱码，查看日志，显示的是 matplotlib 字体的问题。

**Comment by coding-alt** [comment]
问题出在下载的模型上，没有转换带weight的

**Comment by RiseInRose** [comment]
是的👍
